### ISSUE TITLE
Adicionar roteiro de aprendizado de banco de dados relacional

### ISSUE THREAD

**Issue by matheuslc** [casinufsc/meu-professor#2]

**Comment by richardbertozzo** [comment]
Explicando como é, o que é bando de dados relacional

1. http://www.devmedia.com.br/conceitos-fundamentais-de-banco-de-dados/1649
2. https://playcode.com.br/banco-de-dados/sql-banco-dados-iniciantes/

Aprendendo a linguagem SQL:

1. https://www.codecademy.com/learn/learn-sql
2. https://www.sololearn.com/Course/SQL/
Os 2 grátis, iniciando do básico. Existe diversos outros lugares para aprender, apostilas/youtube. Depois podendo continuar em cursos mais avançados no mesmo site tem.
